### ISSUE TITLE
/spawner c minecraft:item

### ISSUE THREAD

**Issue by ziceptor** [trentech/MobSpawners#1]
How to change the subject? Always drops a stone.

**Comment by trentech** [comment]
I don't understand. What do you mean it drops stone?

**Comment by ziceptor** [comment]
1. /spawner c minecraft:item
2. Place spawner
3. Always spawning minecraft:stone
   How to specify a specific block (minecraft:ice, etc) or the material (minecraft:netherbrick, minecraft:brick)?

**Comment by ziceptor** [comment]
Sorry for my terrible English!

**Comment by trentech** [comment]
It's supposed to spawn mobs not items. That's a oversight..and kind of cool. I'll see if I can make this work.
